### ISSUE TITLE
Fix GitHub Actions on Windows

### ISSUE THREAD

**Issue by msrd0** [msrd0/QtWebApp#10]
The CI fails on Windows with some weird linker error. I have no experience whatsoever with Windows, so if someone knows how to fix this, please tell me / open a PR!

**Comment by gladhorn** [comment]
Is there any way for me to reproduce this/trigger a run? Do you have a link to the failure?

**Comment by msrd0** [comment]
Sure, runs are triggered for every pull request, and you can also enable them on any forked repository, but they'll only run on the master branch (unless you configure them to run on other branches too). Links:

 - To the build log: https://github.com/msrd0/QtWebApp/actions
 - To the CI file: https://github.com/msrd0/QtWebApp/blob/master/.github/workflows/build.yml

**Comment by gladhorn** [comment]
Could it be that the g++ version that comes with cocolatey is not sensible? I think I had trouble with that before.
` -- Check for working CXX compiler: C:/ProgramData/chocolatey/bin/g++.exe`

**Comment by gladhorn** [comment]
I think the options are: switch Qt to mingw and get a sensible mingw compiler (which is surprisingly hard with github actions as far as I can tell) or compile with msvc.
