### ISSUE TITLE
using any SQL database in project

### ISSUE THREAD

**Issue by NoWhereMan1979** [msrd0/QtWebApp#3]
dear friend
despite this is newest fork of QtWebApp, i wonder if you can help.
in short sentence, exactly where should i create a database connection in project?
Qt does not allow to use database connection that is created in a controller to be executed in the HttpRequestHandler::service()
even i tried to have db in the HttpRequestHandler itself. but again db queries don't exec inside service() method and all ways throws this error:
QSqlDatabasePrivate::database: requested database does not belong to the calling thread.
best regards
Hameed Abbasi

**Comment by msrd0** [comment]
I'm using https://gitlab.com/msrd0/SPIS (hasn't been updated for a while now) and have the database as private field in my `RequestHandler` class. However I haven't used that particular project in a while now, so I don't know if that's the 2019 way to go.

**Comment by NoWhereMan1979** [comment]
Thank you for quick response.
best wishes.

**Comment by msrd0** [comment]
Feel free to reopen this issue if you have any further questions

**Comment by NoWhereMan1979** [comment]
Thank you for your kindness.
In case of solving the problem i'll notice you.
