### ISSUE TITLE
StaticFileController

### ISSUE THREAD

**Issue by moya-hsy** [msrd0/QtWebApp#35]
QtWebApp/httpserver/staticfilecontroller.cpp
the code here:

	if (!cfg.fileName.isEmpty() && !(docroot.startsWith(":/") || !docroot.startsWith("qrc://"))) {
		// Convert relative path to absolute, based on the directory of the config file.
		if (QDir::isRelativePath(docroot)) {
			QFileInfo configFile(cfg.fileName);
			docroot = QFileInfo(configFile.absolutePath(), docroot).absoluteFilePath();
		}
	}`
The first judgment condition is wrong. Suppose my [docroot] is "../location/staticfiles", it returns false.

**Comment by msrd0** [comment]
Thanks for the report, I pushed a fix to main.
