### ISSUE TITLE
Upstream moved from Website-based ZIP Download to a Git Repository

### ISSUE THREAD

**Issue by StefanFrings** [msrd0/QtWebApp#4]
Hello msrd0,
sorry for the bad title, I cannot change it anymore. I did not find contact information, otherwise I would have sent you an email.

I just wanted to tell you that QtWebApp is now officially available on my own site on https://github.com/StefanFrings/QtWebApp/

As far as I can see, you added support for CMAKE, which is a good reason to keep your repo. Right?

**Comment by msrd0** [comment]
That is correct, the main point of creating this fork was CMake support. Other than that, I believe I changed a lot in the way settings work, and also not writing `use` statements in header files which kinda defeats the purpose of namespaces IMHO. You can probably see all the changes I did pretty easily by looking at the [diff between master and upstream](https://github.com/msrd0/qtwebapp/compare/upstream...master).

Feel free to integrate some or all of the changes into your library if you like them. I am unlikely to continue making further changes as I found Rust being a far superior programming language to C++.
